# Generated by Django 4.0.3 on 2022-03-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id_code', models.TextField(primary_key=True, serialize=False)),
                ('ammo_symbol', models.TextField()),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ammo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField(primary_key=True, serialize=False)),
                ('effect_on_target', models.TextField(blank=True, null=True)),
                ('flat_modifier', models.IntegerField()),
                ('pain_modifier', models.IntegerField()),
                ('head_description', models.TextField(blank=True, null=True)),
                ('torso_description', models.TextField(blank=True, null=True)),
                ('r_arm_description', models.TextField(blank=True, null=True)),
                ('l_arm_description', models.TextField(blank=True, null=True)),
                ('leg_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'damage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('range', models.IntegerField()),
                ('modifier', models.IntegerField()),
            ],
            options={
                'db_table': 'difficulty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id_code', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('modifier_10m', models.IntegerField(blank=True, null=True)),
                ('modifier_20m', models.IntegerField(blank=True, null=True)),
                ('modifier_30m', models.IntegerField(blank=True, null=True)),
                ('modifier_40m', models.IntegerField(blank=True, null=True)),
                ('modifier_60m', models.IntegerField(blank=True, null=True)),
                ('modifier_80m', models.IntegerField(blank=True, null=True)),
                ('modifier_100m', models.IntegerField(blank=True, null=True)),
                ('modifier_150m', models.IntegerField(blank=True, null=True)),
                ('modifier_200m', models.IntegerField(blank=True, null=True)),
                ('modifier_250m', models.IntegerField(blank=True, null=True)),
                ('modifier_300m', models.IntegerField(blank=True, null=True)),
                ('modifier_400m', models.IntegerField(blank=True, null=True)),
                ('modifier_600m', models.IntegerField(blank=True, null=True)),
                ('modifier_1000m', models.IntegerField(blank=True, null=True)),
                ('modifier_1500m', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weapon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ranged',
            fields=[
                ('id_code', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('magazine', models.IntegerField()),
                ('misfire_roll', models.IntegerField()),
                ('celnosc_w_procentach', models.IntegerField(blank=True, null=True)),
                ('zasieg', models.IntegerField(blank=True, null=True)),
                ('fire_rate', models.IntegerField(blank=True, null=True)),
                ('attack_type', models.TextField(blank=True, null=True)),
                ('reload', models.IntegerField(blank=True, null=True)),
                ('punkty_przebicia', models.IntegerField()),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('holster', models.IntegerField()),
                ('price', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('actions', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('ammo', models.ForeignKey(db_column='ammo', on_delete=django.db.models.deletion.DO_NOTHING, to='items.ammo')),
                ('damage', models.ForeignKey(db_column='damage', on_delete=django.db.models.deletion.CASCADE, to='items.damage')),
                ('weapon_class', models.ForeignKey(db_column='weapon_class', on_delete=django.db.models.deletion.CASCADE, to='items.weapon')),
            ],
            options={
                'db_table': 'ranged',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ammo',
            name='crafting_difficulty',
            field=models.ForeignKey(db_column='crafting_difficulty', on_delete=django.db.models.deletion.CASCADE, to='items.difficulty'),
        ),
    ]
