# Generated by Django 4.0.2 on 2022-06-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_ammo_image_remove_ranged_image_ammo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='thumbnail',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='ammo'),
        ),
        migrations.AlterField(
            model_name='ranged',
            name='thumbnail',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='ranged'),
        ),
    ]
